version: "3.7"

services:
  # https://github.com/emscripten-core/emsdk/blob/main/docker/README.md
  emscripten:
    build:
      context: .
    # Allow writing to host filesystem as non-root
    user: ${DOCKER_USER:-1000:1000}
    working_dir: /app
    volumes:
      - ./:/app
      - emscripten-cache:/emsdk/upstream/emscripten/cache

  # fix version to use clang-format
  clang:
    image: silkeh/clang:14-stretch
    user: ${DOCKER_USER:-1000:1000}
    working_dir: /app
    volumes:
      - ./:/app

volumes:
  emscripten-cache:
