version: "3.5"

services:
  # for testing open-telemetry integration locally
  # https://www.jaegertracing.io/docs/1.39/getting-started/
  jaeger:
    image: jaegertracing/all-in-one:1.39
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      # OTLP over HTTP http://localhost:4318
      - 4318:4318
      # UI http://localhost:16686
      - 16686:16686
    profiles: ["tools"]
