name = "youtube-dl-web"

main = "./dist/cloudflare/index.js"
assets = "./dist/cloudflare/bucket"
workers_dev = true
no_bundle = true
compatibility_date = "2023-04-20"
compatibility_flags = [ "nodejs_compat" ]

# counter default rule https://github.com/cloudflare/workers-sdk/blob/113fb7fe86cde0c43a7efa7fc2e58ec8c55d8267/packages/wrangler/src/module-collection.ts#L43
# to avoid wrangler confusing client wasm as server module and uploading it to worker
# TODO: such config not allowed by wrangler anyway?
[[rules]]
type = "CompiledWasm"
globs = []
fallthrough = false

# npx wrangler kv:namespace create kv
# npx wrangler kv:namespace create kv --env staging
# npx wrangler kv:namespace create kv --env staging --preview
[[kv_namespaces]]
binding = "kv"
id = "b69d95156a074661b3f2e7bac4a644ca"

[[env.staging.kv_namespaces]]
binding = "kv"
id = "329c9104766d4e7289f879aef5a93d4f"

[[env.local.kv_namespaces]]
binding = "kv"
id = "__dummy-unused"
preview_id = "dd598af7e7764ea49de46a5ca794de04"

[vars]
OTEL_SERVICE_NAME = "youtube-dl-web"
OTEL_TRACES_EXPORTER = "otlp"
OTEL_EXPORTER_OTLP_ENDPOINT = "https://otlp.nr-data.net:4318"
# https://developers.cloudflare.com/workers//wrangler/commands/#secret
# npx wrangler secret put OTEL_EXPORTER_OTLP_TRACES_HEADERS
# OTEL_EXPORTER_OTLP_TRACES_HEADERS = "api-key=xxx"

[env.staging.vars]
OTEL_SERVICE_NAME = "youtube-dl-web-staging"
OTEL_TRACES_EXPORTER = "otlp"
OTEL_EXPORTER_OTLP_ENDPOINT = "https://otlp.nr-data.net:4318"
# npx wrangler secret put OTEL_EXPORTER_OTLP_TRACES_HEADERS --env staging
# OTEL_EXPORTER_OTLP_TRACES_HEADERS = "api-key=xxx"

[env.local.vars]
# tweak variables for local testing
# OTEL_SERVICE_NAME = "youtube-dl-web-local"
# OTEL_TRACES_EXPORTER = "console"
# OTEL_TRACES_EXPORTER = "otlp"
# OTEL_EXPORTER_OTLP_ENDPOINT = "https://otlp.nr-data.net:4318"
# OTEL_EXPORTER_OTLP_TRACES_HEADERS = "api-key=xxx"
