name: health-check
"on":
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
jobs:
  health-check:
    runs-on: ubuntu-20.04
    container:
      image: badouralix/curl-jq
    steps:
      - name: GET /healthz
        run: |
          curl -sf https://youtube-dl-web.hiro18181.workers.dev/healthz
      - name: POST /api/metadata
        run: |
          curl -sf https://youtube-dl-web.hiro18181.workers.dev/trpc/getVideoMetadata -H 'content-type: application/json' --data-raw '[{ "id": "https://www.youtube.com/watch?v=rv4wf7bzfFE" }]' | jq -r --exit-status '.value.videoInfo.title'
